version: 0.0
os: linux
files:
  - source: ./GestaoNormas-0.0.1.jar
    destination: /tmp
hooks:
  ApplicationStart:
    - location: start_server.sh
      runas: root
  ApplicationStop:
    - location: stop_server.sh
      runas: root