version: 0.0
os: linux
files:
  - source: ./GestaoNormas-0.0.1.jar
    destination: /tmp
hooks:
  BeforeInstall:
    - location: runapp.sh
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      runas: root